# Generated by Django 3.1 on 2020-08-16 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobileinfo',
            name='android_id',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='mobileinfo',
            name='id',
            field=models.CharField(default='default', max_length=200, primary_key=True, serialize=False),
        ),
    ]
